using Newtonsoft.Json;

namespace PayGram.Public
{
	public class PaygramRequest : IPaygramRequest
	{
		public long RequestId { get; set; }
		/// <summary>
		/// The UserId at the client side that originated this request
		/// Null if this request was not generated by the user
		/// </summary>
		public string? UserCliId { get; set; }
		public PaygramRequest()
		{
			RequestId = 0;
		}
		public PaygramRequest(long id)
		{
			RequestId = id;
		}
		public string ToJson()
		{
			return JsonConvert.SerializeObject(this, Formatting.Indented,
													new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate });
		}
	}
	public class RequestUpdateBusiness : PaygramRequest
	{
		public long Id { get; set; }
		public string Name { get; set; }
		public string? Description { get; set; }
		public string? ImageUrl { get; set; }
		public string? LocationUrl { get; set; }
		public bool IsOnline { get; set; }
		public bool Approved { get; set; }
	}
}
